src/main/java/wooteco/chess/SparkChessApplication.java
src/main/java/wooteco/chess/controller/ChessController.java
src/main/java/wooteco/chess/dao/GameDao.java
src/main/java/wooteco/chess/dao/JDBCTemplate.java
src/main/java/wooteco/chess/domain/GameManager.java
src/main/java/wooteco/chess/domain/board/Board.java
src/main/java/wooteco/chess/domain/board/BoardFactory.java
src/main/java/wooteco/chess/domain/piece/Bishop.java
src/main/java/wooteco/chess/domain/piece/King.java
src/main/java/wooteco/chess/domain/piece/Knight.java
src/main/java/wooteco/chess/domain/piece/Pawn.java
src/main/java/wooteco/chess/domain/piece/Piece.java
src/main/java/wooteco/chess/domain/piece/Queen.java
src/main/java/wooteco/chess/domain/piece/Rook.java
src/main/java/wooteco/chess/domain/position/Row.java
src/main/java/wooteco/chess/exceptions/IllegalMovementException.java
src/main/java/wooteco/chess/exceptions/TurnMisMatchException.java
src/main/java/wooteco/chess/service/GameManagerService.java
src/main/resources/templates/board.hbs
src/main/resources/templates/error.hbs
src/main/resources/templates/index.hbs
src/test/java/wooteco/chess/domain/piece/KnightTest.java

[히로] 체스 - 스프링 실습 2단계 제출합니다.

---

src/main/java/wooteco/chess/database/DataSource.java

스프링을 이번에 처음 다뤄봐서 아직 부족한 점이 많습니다.
부족한 부분 많이 지적해주시면 감사하겠습니다 :)

[스티치] 체스 스프링 실습 2단계 미션 제출입니다

---

src/main/java/wooteco/chess/SparkChessApplication.java
src/main/java/wooteco/chess/controller/ChessController.java
src/main/java/wooteco/chess/dao/GameInfoDAO.java
src/main/java/wooteco/chess/dao/UserDAO.java
src/main/java/wooteco/chess/domain/piece/Pawn.java
src/main/java/wooteco/chess/service/ChessService.java
src/main/java/wooteco/chess/util/DBConnector.java
src/main/resources/static/js/board.js

[로운] 체스 스프링 실습 2단계 제출합니다.

---

src/main/java/wooteco/chess/SparkChessApplication.java
src/main/java/wooteco/chess/controller/SpringChessController.java
src/main/java/wooteco/chess/controller/SpringChessRestController.java
src/main/java/wooteco/chess/repository/GameRepository.java
src/main/java/wooteco/chess/repository/jdbc/JDBCGameRepository.java
src/main/java/wooteco/chess/service/GameService.java
src/test/java/wooteco/chess/repository/BlackKingCatchedGameRepository.java
src/test/java/wooteco/chess/repository/FinishedDrawGameRepository.java
src/test/java/wooteco/chess/repository/ReadyGameRepository.java
src/test/java/wooteco/chess/repository/StartedGameRepository.java
src/test/java/wooteco/chess/repository/WhiteMoreScoreGameRepository.java
src/test/java/wooteco/chess/service/GameServiceTest.java

안녕하세요~ 임루트입니다.
체스 스프링 실습 2단계 리뷰 부탁드립니다~!^^

[임루트] 체스 스프링 실습 2단계 제출합니다.

---

src/main/java/wooteco/chess/SpringChessApplication.java

안녕하세요, WOO!
미션 2단계에 대한 commit이 1단계에 같이 머지되어 있습니다.
불편하시겠지만 미션 1단계의 commit을 참고 부탁드립니다... 😭 
이번 리뷰도 잘 부탁드립니다!

[무늬] 체스 스프링 실습 2단계 제출합니다.

---

src/main/java/wooteco/chess/SparkChessApplication.java
src/main/java/wooteco/chess/controller/ChessController.java
src/main/java/wooteco/chess/dao/GameInfoDAO.java
src/main/java/wooteco/chess/dao/UserDAO.java
src/main/java/wooteco/chess/domain/piece/Pawn.java
src/main/java/wooteco/chess/service/ChessService.java
src/main/java/wooteco/chess/util/DBConnector.java
src/main/resources/static/js/board.js

[히히] Chess Spring 2단계 제출합니다 :)

---

src/main/java/wooteco/chess/controller/SpringChessController.java
src/main/java/wooteco/chess/db/ChessPiece.java
src/main/java/wooteco/chess/db/ChessPieceRepository.java
src/main/java/wooteco/chess/db/MoveHistory.java
src/main/java/wooteco/chess/db/MoveHistoryRepository.java
src/main/java/wooteco/chess/service/SpringChessService.java
src/main/resources/application.properties
src/main/resources/static/js/chess_web.js
src/main/resources/templates/game_room.hbs
src/main/resources/templates/index.hbs

[쪼밀리] 체스 스프링 3단계 제출

---

README.md
src/main/java/wooteco/chess/controller/SpringChessController.java
src/main/java/wooteco/chess/entity/History.java
src/main/java/wooteco/chess/entity/HistoryRepository.java
src/main/java/wooteco/chess/service/SpringDataJDBCChessService.java
src/main/resources/application.properties
src/main/resources/schema.sql

[라빈] 체스 스프링 3단계 미션 제출합니다.

---

README.md
src/main/java/wooteco/chess/controller/SpringChessController.java
src/main/java/wooteco/chess/entity/History.java
src/main/java/wooteco/chess/entity/HistoryRepository.java
src/main/java/wooteco/chess/service/SpringDataJDBCChessService.java
src/main/resources/application.properties
src/main/resources/schema.sql

히히 두번째 리뷰도 고마워요!
추후 수정될 여지가 있고, 의도를 가지고 남겨두었기에 아직 반영하지 않았지만 제 코드에 대해 다시 생각할 수 있는 기회가 되었습니다😁
세번째 미션 리뷰도 부탁드려요!
연휴이니만큼 시간을 가지고 천천히 해주셔도 괜찮습니다! 화이팅화이팅.
이번 미션은 History 엔티티를 이용하여 JDBC와 연동해보았습니다.
테이블이 1개 뿐이라 수정사항이 생각보다 적었네요..!
연휴에도 즐겁게 보내요 우리😉

[토니] 체스 스프링 3단계 미션 제출합니다.

---

src/main/java/wooteco/chess/domain/entity/ChessGameEntity.java
src/main/java/wooteco/chess/dto/ChessGameDto.java
src/main/java/wooteco/chess/service/ChessService.java
src/test/java/wooteco/chess/domain/entity/ChessGameEntityTest.java
src/test/java/wooteco/chess/domain/game/ChessGameTest.java
src/test/java/wooteco/chess/domain/repository/ChessRepositoryTest.java

안녕하세요. 카프카입니다.
연휴 잘 보내고 계신가요?
사정이 생겨 리뷰 보내는 것이 조금 늦어졌네요.
테스트 코드 추가 및 일부 로직 변경이 있습니다.
다만 auto_increments를 통한 로직을 3단계에서 구현했기 때문에
이번 단계에서는 큰 변화가 없습니다.
감사합니다.

[카프카] 체스 스프링 미션 4단계 제출합니다.

---

src/main/java/wooteco/chess/controller/spring/RoomController.java
src/main/java/wooteco/chess/service/spring/SpringGameService.java
src/main/resources/templates/createNewGame.hbs
src/main/resources/templates/index.hbs

[타미] 4단계 제출합니다.

---

src/main/java/wooteco/chess/controller/SpringChessController.java
src/main/java/wooteco/chess/db/ChessPiece.java
src/main/java/wooteco/chess/db/ChessPieceRepository.java
src/main/java/wooteco/chess/db/MoveHistory.java
src/main/java/wooteco/chess/db/MoveHistoryRepository.java
src/main/java/wooteco/chess/service/SpringChessService.java
src/main/resources/application.properties
src/main/resources/static/js/chess_web.js
src/main/resources/templates/game_room.hbs
src/main/resources/templates/index.hbs

[두강] 스프링 실습 3단계 미션 제출합니다.

---

src/main/java/wooteco/chess/controller/SpringController.java
src/main/java/wooteco/chess/service/ChessService.java
src/main/resources/static/css/admin-room.css
src/main/resources/static/css/style.css
src/main/resources/static/js/modules/AdminRoom.js
src/main/resources/static/script.js
src/main/resources/static/ui/Modal.js
src/main/resources/static/utils/constants.js
src/main/resources/static/utils/templates.js
src/main/resources/templates/chess.hbs
src/main/resources/templates/index.hbs

안녕하세요 레베카 :)
드디어 마지막 제출이네요 🎉🎉 
이번 미션도 잘 부탁드립니다!

[시카] 체스 - 스프링 실습 4단계 제출합니다.

---

src/main/java/wooteco/chess/controller/ChessRestController.java
src/main/java/wooteco/chess/controller/IndexController.java
src/main/java/wooteco/chess/entity/ChessGameEntity.java
src/main/java/wooteco/chess/entity/ChessGameRepository.java
src/main/java/wooteco/chess/entity/RandomUUIDProvider.java
src/main/java/wooteco/chess/service/ChessGameService.java
src/main/resources/application.properties
src/main/resources/schema.sql
src/main/resources/static/game.js
src/main/resources/static/index.js
src/main/resources/templates/game.hbs
src/test/java/wooteco/chess/controller/ChessRestControllerTest.java
src/test/java/wooteco/chess/controller/IndexControllerTest.java
src/test/java/wooteco/chess/entity/ChessGameRepositoryTest.java

안녕하세요 동글, 4단계에서는 ID를 UUID로 변경하고 몇가지 테스트를 추가해 보았습니다. 3단계까지 리뷰하시느라 고생 많으셨습니다. 4단계도 잘 부탁드립니다..!!

[알트] 체스 스프링 실습 4단계 제출합니다.

---

src/main/resources/static/js/chess.js
src/main/resources/templates/index.hbs

[카일] 체스 4단계 제출합니다.

---

src/main/java/chess/dto/view/GameInformationDto.java
src/main/java/chess/model/domain/board/CastlingSetting.java
src/main/java/chess/model/domain/board/ChessBoard.java
src/main/java/chess/model/domain/board/ChessGame.java
src/main/java/chess/model/domain/board/TeamScore.java
src/main/java/chess/model/repository/ChessGameEntity.java
src/main/java/chess/util/TFAndYNConverter.java
src/test/java/chess/SpringChessApplicationTests.java
src/test/java/chess/model/domain/board/TeamScoreTest.java
src/test/java/chess/util/TFAndYNConverterTest.java

안녕하세요! 비밥!
드디어 마지막 미션이네요!
그동안 너무 고마웠어요~
방의 경우엔 기존에도 지원 가능했던 부분이라 별로 수정한 부분은 없습니다!
많은 리뷰 부탁드려요!

[제이미] 4단계 미션 제출합니다.

---

src/main/java/wooteco/chess/controller/BoardController.java
src/main/java/wooteco/chess/domain/user/UserRepository.java

이전 Pr 실수로 merge를 눌러 다시 보냅니다. ㅠㅠ
상호 리뷰어의 피드백은 모두 반영했습니다.

[보스독] 체스 - 스프링 실습 4단계 제출합니다.

---

src/main/java/chess/SparkChessApplication.java
src/main/java/chess/SpringChessApplication.java
src/main/java/chess/controller/ChessController.java
src/main/java/chess/controller/SpringChessControllerAdvice.java
src/main/java/chess/domain/dao/CommandDao.java
src/main/java/chess/domain/dao/CommandDaoImpl.java
src/main/java/chess/domain/dao/HistoryDao.java
src/main/java/chess/domain/dao/HistoryDaoImpl.java
src/main/java/chess/domain/dao/SparkCommandDao.java
src/main/java/chess/domain/dao/SparkHistoryDao.java
src/main/java/chess/domain/dto/ErrorMessageDto.java
src/main/java/chess/domain/dto/ExceptionResponseDto.java
src/main/java/chess/domain/dto/MoveResponseDto.java
src/main/java/chess/domain/repository/ChessGameRepository.java
src/main/java/chess/domain/repository/ChessGameRepositoryImpl.java
src/main/java/chess/service/SparkChessService.java
src/main/java/chess/service/SpringChessService.java
src/main/java/chess/view/ModelView.java
src/main/resources/application.properties
src/main/resources/public/js/move.js
src/main/resources/templates/chessGame.hbs
src/main/resources/templates/play.hbs
src/test/java/chess/domain/dao/CommandDaoImplTest.java
src/test/java/chess/domain/dao/HistoryDaoImplTest.java
src/test/java/chess/domain/dao/HistoryDaoTest.java
src/test/java/chess/domain/dao/SparkCommandDaoTest.java
src/test/java/chess/domain/dao/SparkHistoryDaoTest.java

안녕하세요! 휴! 
와이비입니다. 반갑습니다. 
원래 추가 기능을 구현을 하려고하였으나, FrontEnd부터 DataBase구조까지 전부 바꿔야하는 점과 인증에 관련된 부분은 다음 미션에서 다룬다고 알고 있기 때문에 일단은 진행하지 않게 되었습니다.
말씀해주신데로, @ControllerService와 @ExceptionHandler를 먼저 사용하게 되었습니다. 
예외처리를 해주지 않아서 코드가 깔끔하게 작성이되면서, 동시에 Controller에서의 모든 오류를 한 가지 방법으로 묶을 수 있는 것이 매력인 것 같습니다.
Exception을 사용할 경우에는 더욱 확장해서 사용할 수 있을 것 같아요!
이번에 저는 Exception Handler의 특성을 살펴보기 되면서, ErrorMessage전용 Dto를 다음과 같이 만들게 되었습니다.
```java
@ExceptionHandler(DataException.class)
public ResponseEntity<ErrorMessageDto> dataExceptionResponse(DataException dataException) {
String message = dataException.getMessage();
ErrorMessageDto errorMessageDto = new ErrorMessageDto(message);
return ResponseEntity.status(400)
.body(errorMessageDto);
}
public class ErrorMessageDto {
private final String errorMessage;
public …
```

[Spring 체스 - 3단계] 와이비(허영범) 미션 제출합니다.

---

Readme.md
src/main/java/chess/controller/SpringController.java
src/main/resources/public/js/component/chessBoard.js
src/main/resources/public/js/component/restartBtn.js
src/main/resources/public/js/component/roomListPage.js
src/main/resources/public/js/component/startBtn.js
src/main/resources/public/js/service/chessService.js

이번 미션은 step1때 구현되어 있는 기능이 많아서 많이 손보지는 않았어요
전체적인 개념에 대해서 학습하는데 더 치중했고 미션과는 상관 없지만 몇 가지 의문점이 생겨서 질문드릴게요
구현된 체스 페이지가 있는데
기능을 수행할 때에는 정상적으로 동작합니다
그런데 직접 URL로 접근할 경우에는 
이런식으으로 UI가 제대로 구현되지 않아서  문제가 발생해요
로직상으로 
메인페이지에서 방 클릭 -> 렌더링 과정에서 UI 생성 -> 게임 진행 가능
이와 같은 순서로 동작하는데
"방 클릭" 과정을 제외하고 바로 URL로 접근할 경우에 Raw 데이터가 노출되는 문제는 어느 쪽의 문제일까요?
1. JS에서 로직을 수정해야한다
2. URL로 접근하는 "비정상적인" 요청을 필터링 해야 한다( 그런데 다른 많은 웹사이트들은 이런 URL 접근 방식도 정상적으로 동작함)
3. URL 디자인이 잘못되었다
어느쪽에 문제 해결의 책임이 있는지 궁금해서 질문드립니다.

[Spring 체스 - 3단계] 마갸(정찬영) 미션 제출합니다.

---

README.md
src/main/java/chess/controller/config/ChessWebConfiguration.java
src/main/java/chess/controller/web/ChessRestController.java
src/main/java/chess/controller/web/ChessViewController.java
src/main/java/chess/controller/web/ExceptionController.java
src/main/java/chess/database/dao/SpringRoomDao.java
src/main/java/chess/service/SpringChessService.java
src/main/resources/application-test.properties
src/main/resources/application.properties
src/main/resources/schema.sql
src/main/resources/static/js/game.js
src/main/resources/templates/index.hbs
src/main/resources/templates/repository.hbs
src/test/java/chess/controller/web/ChessRestControllerTest.java
src/test/java/chess/controller/web/ChessViewControllerTest.java
src/test/java/chess/database/dao/SpringRoomDaoTest.java
src/test/resources/application-test.properties
src/test/resources/schema.sql

안녕하세요 지노!!
체스 3단계로 찾아 뵙게 되었네요!!
1, 2단계 때 이미 방 기능을 구현 했기에 크게 달라진 부분은 없는데요.
지노 피드백대로 코드 수정 + Controller 테스트 코드 추가를 해보았습니다.
Mock에 대한 개념이나 MockMvc 사용법 등 Controller 테스트 하는 부분이 생각보다 어려워 도움을 받아가며 진행했는데요!😂😂
현재 Controller 테스트는 Service + Dao를 합친 통합 테스트 방식으로 코드를 작성했습니다.
작성하다보니 이런 방식으로 Controller 테스트를 하는구나하고 조금은 감을 잡게 되었습니다..!
지금 작성한 방식이 괜찮은지 지노의 피드백 부탁드립니다!!
감사합니다~~~

[Spring 체스 - 3단계] 오즈(오주형) 미션 제출합니다.

---

src/main/java/chess/controller/dto/BoardDto.java
src/main/java/chess/controller/web/GameController.java
src/main/java/chess/controller/web/RoomController.java
src/main/resources/public/script/main.js
src/main/resources/templates/mainPage.hbs

안녕하세요 미립!! 1,2 단계 마지막으로 주신 리뷰 바탕으로 리팩토링 진행해봤어요 :)
내용은 아래와 같습니다
> 1. final 키워드는 재할당만 막고 값의 추가, 제거는 가능하다.
레벨 1 초반에 배웠는데..아는 것을 잘 적용하자…!!!  UnmodifiableMap으로 값을 변경할 수 없도록 변경했습니다!
> 2. @GetMapping(“/load/{roomId}”) -> @GetMapping(“/{roomId}”)
load를 게임을 조회한다는 것으로 보면 굳이 필요하지 않고 HTTP METHOD를 통해 표현할 수 있으므로 제거했습니다 !
> 3. HTTP METHOD로 표현하기 힘든 행위는 맨 뒤에서 표현한다. 
이 부분도 리뷰 해주신 것 처럼 games/{id}/move로 표현하도록 수정했습니다 !
* 스프링 사용에 집중하고 더 공부해보자고 생각해 추가미션은 진행하지 않기로 했습니다.. 양해 부탁드려요!

[Spring 체스 - 3단계] 욘(김영빈) 미션 제출합니다.

---

build.gradle
src/main/java/chess/controller/spring/GridController.java
src/main/java/chess/controller/spring/MoveController.java
src/main/java/chess/controller/spring/RoomController.java
src/main/java/chess/controller/spring/params/Page.java
src/main/java/chess/dao/GridDAO.java
src/main/java/chess/dao/PieceDAO.java
src/main/java/chess/dao/RoomDAO.java
src/main/java/chess/dto/GridDto.java
src/main/java/chess/dto/PieceDto.java
src/main/java/chess/modelmapper/PieceMapper.java
src/main/java/chess/service/ChessService.java
src/main/resources/public/js/component/roomListPage.js
src/test/java/chess/controller/spring/GridControllerTest.java
src/test/java/chess/controller/spring/MoveControllerTest.java
src/test/java/chess/controller/spring/RoomControllerTest.java
src/test/java/chess/domain/dao/RoomDAOTest.java

안녕하세요 제이! 제리에요🐭
이번 미션 기간동안 스프링에 대해서 공부한다고 정신이 없네요...ㅠㅠ 
처음에는 레시피처럼 스프링을 쓰다가 차근차근 원리를 공부해나가니
스프링이 어떻게 작동하는 지 머릿속에서 생각하면서 코드를 짤 수 있어서 정말 좋은 것 같애요!!
최근에는 스프링 컨테이너와 스프링 빈의 원리에 대해서 공부함으로써
스프링이 자바로만 코딩했을 때에 불편한 점을 정말 많이 보완해주고, 편리하게 코딩을 할 수 있게 도와주고 있다는 것을 많이 느꼈어요!
이번 스프링을 공부함에 있어서 이번 미션과 함께 같이 또 공부하면서 적용해보면 좋은 부분이 있다면 얘기해주시면, 
얘기해주신 내용 바탕으로 또 찾아서 공부해보겠습니다😄

[Spring 체스 - 3단계] 제리(박재성) 미션 제출합니다.

---

.gitignore
src/main/java/chess/Application.java
src/main/java/chess/domain/command/dao/MoveCommandDao.java
src/main/java/chess/domain/game/ChessGame.java
src/main/java/chess/domain/game/dao/ChessGameDao.java
src/main/java/chess/service/ChessService.java
src/main/java/chess/web/controller/ChessAdvice.java
src/main/java/chess/web/controller/ChessApiController.java
src/main/java/chess/web/controller/ChessController.java
src/main/resources/static/js/game.js
src/main/resources/static/js/lobby.js
src/test/java/chess/domain/game/ChessGameTest.java
src/test/java/chess/domain/game/dao/ChessGameDaoTest.java

안녕하세요 김고래!!
제가 3단계 요구사항은 이미 적용한 상태라 저번 리뷰의 피드백들만 반영하고 다시 리뷰요청 드려요~!!

[Spring 체스 - 3단계] 조이(김주원) 미션 제출합니다.

---

docs/README.md
src/main/java/chess/SpringChessApplication.java
src/main/java/chess/config/BeanConfig.java
src/main/java/chess/repository/PlayLogRepository.java
src/test/java/chess/controller/SpringChessApiControllerTest.java
src/test/java/chess/controller/SpringChessControllerTest.java
src/test/java/chess/repository/PlayLogRepositoryTest.java
src/test/java/chess/repository/RoomRepositoryTest.java
src/test/java/chess/repository/UserRepositoryTest.java
src/test/java/chess/service/SpringChessServiceTest.java
src/test/resources/tableInit.sql

3단계 요구사항은 이미 구현되어있어서, 
1,2,단계때 피드백 해주신, 
- Service 테스트 코드 추가
- `@Bean` 을 Class로 분리 
위 두가지의 작업을 진행했어요.
스프링을 처음으로 학습한 지금 현상황에선, 추가미션을 진행하는것보다 이번 미션을 진행하면서 학습한 스프링을 복습할 시간이 필요하네요.
한꺼번에 너무 많은 정보를 습득했다보니 대충 넘어간것도 많고, 지식이 너무 파편화가 되어있어 서적이나 인터넷 강의로 보충하려고해요.
이번 리뷰도 잘 부탁드려요.

[Spring 체스 - 3단계] 포츈(정윤성) 미션 제출합니다.
